name: claro_manin_expositor
description: Una aplicación Flutter mínima para exponer una camiseta.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 # Versión compatible con null safety la otra me daba errores
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
